server {
  listen 80;

  location / {
    root   /usr/share/nginx/html;
    index  index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  # Add other locations for API proxying if needed, though for Cloud Run
  # it's better to have two separate services that talk to each other internally.
}
